name: Discord Notification

on:
  push:
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - '.gitattributes'
      - 'config.ld'
      - 'README.md'
      - 'LICENSE'
      - 'Rotations/Old/**'
      - 'Rotations/sample rotation.lua'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Send notification to Discord
      uses: Mist3r-Robot/classic-discord-webhook@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
