name: Generate LDoc Documentation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Setup Lua
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: "5.1"

    - name: Setup Lua Rocks
      uses: leafo/gh-actions-luarocks@v4

    - name: Setup dependencies
      run: luarocks install ldoc

    - name: Build docs
      run: ldoc .

    - name: Copy custom ldoc.css
      run: cat .github/assets/css/custom.css >> ./ldoc.css

    - name: Copy fontawesome-all.min.css
      run: cp .github/assets/css/fontawesome-all.min.css ./

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: docs
        token: ${{ secrets.GITHUB_TOKEN }}
