name: Generate LDoc Documentation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Generate Dynamic Documentation
      run: python .github/generate_dynamic_docs.py

    - name: Setup Lua
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: "5.1"

    - name: Setup Lua Rocks
      uses: leafo/gh-actions-luarocks@v4

    - name: Setup dependencies
      run: luarocks install ldoc

    - name: Print current directory
      run: pwd

    - name: List template directory contents
      run: ls -al .github/custom_templates

    - name: Build docs
      run: ldoc --template .github/custom_templates/ldoc/custom_template.ldoc .

    - name: Append Dynamic Documentation to LDoc Output
      run: cat DOCS.md >> ./docs/index.html  # Adjust the path if LDoc outputs to a different file

    - name: Deploy
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
